# general
ROOT: ${root_data_dir}/eth3d
dataset_metadata_dir: ${mapanything_metadata_dir}

# test
test:
  dataset_str:
    "ETH3DWAI(
      resolution=${dataset.eth3d.test.dataset_resolution},
      principal_point_centered=${dataset.eth3d.test.principal_point_centered},
      seed=${dataset.eth3d.test.seed},
      transform='${dataset.eth3d.test.transform}',
      data_norm_type='${dataset.eth3d.test.data_norm_type}',
      ROOT='${dataset.eth3d.ROOT}',
      dataset_metadata_dir='${dataset.eth3d.dataset_metadata_dir}',
      variable_num_views=${dataset.eth3d.test.variable_num_views},
      num_views=${dataset.eth3d.test.num_views},
      covisibility_thres=${dataset.eth3d.test.covisibility_thres})"
  dataset_resolution: ${dataset.resolution.val.eth3d}
  principal_point_centered: ${dataset.principal_point_centered}
  seed: 777
  transform: 'imgnorm'
  data_norm_type: ${model.data_norm_type}
  variable_num_views: ${dataset.test.variable_num_views}
  num_views: ${dataset.num_views}
  covisibility_thres: 0.025