### Config for default training resolutions
# To override, either change this file, or create a separate config for your model/experiment
# and inherit + override this config (see vggt.yaml for an example). 
# The latter is the cleaner / recommended approach

# Train resolution
# default is (518, 518) like VGGT, but run-specific configs can override
train: (518, 518)
# Val/Test resolution
val:
  blendedmvs: (518, 392)
  mvs_synth: (518, 294)
  scannetppv2: (518, 336)
  eth3d: (518, 336)
  unrealstereo4k: (518, 294)
  mpsd: (518, 294)