# general
ROOT: ${root_data_dir}/mvs_synth
dataset_metadata_dir: ${mapanything_metadata_dir}

# train args
train:
  dataset_str:
    "MVSSynthWAI(
      split='${dataset.mvs_synth.train.split}',
      resolution=${dataset.mvs_synth.train.dataset_resolution},
      principal_point_centered=${dataset.mvs_synth.train.principal_point_centered},
      aug_crop=${dataset.mvs_synth.train.aug_crop},
      transform='${dataset.mvs_synth.train.transform}',
      data_norm_type='${dataset.mvs_synth.train.data_norm_type}',
      ROOT='${dataset.mvs_synth.ROOT}',
      dataset_metadata_dir='${dataset.mvs_synth.dataset_metadata_dir}',
      overfit_num_sets=${dataset.mvs_synth.train.overfit_num_sets},
      variable_num_views=${dataset.mvs_synth.train.variable_num_views},
      num_views=${dataset.mvs_synth.train.num_views},
      covisibility_thres=${dataset.mvs_synth.train.covisibility_thres})"
  split: 'train'
  num_views: ${dataset.num_views}
  variable_num_views: ${dataset.train.variable_num_views}
  covisibility_thres: 0.25
  dataset_resolution: ${training.resolution.train}
  principal_point_centered: ${dataset.principal_point_centered}
  aug_crop: 16
  transform: 'colorjitter+grayscale'
  data_norm_type: ${model.data_norm_type}
  overfit_num_sets: null

# val args
val:
  dataset_str:
    "MVSSynthWAI(
      split='${dataset.mvs_synth.val.split}',
      resolution=${dataset.mvs_synth.val.dataset_resolution},
      principal_point_centered=${dataset.mvs_synth.val.principal_point_centered},
      seed=${dataset.mvs_synth.val.seed},
      transform='${dataset.mvs_synth.val.transform}',
      data_norm_type='${dataset.mvs_synth.val.data_norm_type}',
      ROOT='${dataset.mvs_synth.ROOT}',
      dataset_metadata_dir='${dataset.mvs_synth.dataset_metadata_dir}',
      overfit_num_sets=${dataset.mvs_synth.val.overfit_num_sets},
      variable_num_views=${dataset.mvs_synth.val.variable_num_views},
      num_views=${dataset.mvs_synth.val.num_views},
      covisibility_thres=${dataset.mvs_synth.val.covisibility_thres})"
  split: 'val'
  dataset_resolution: ${training.resolution.val.mvs_synth}
  principal_point_centered: ${dataset.principal_point_centered}
  seed: 777
  transform: 'imgnorm'
  data_norm_type: ${model.data_norm_type}
  overfit_num_sets: null
  variable_num_views: ${dataset.val.variable_num_views}
  num_views: ${dataset.num_views}
  covisibility_thres: 0.25