logging_dir: ${logging_dir}
# Wandb
wandb:
  project: ???
  entity: ???
# How many steps between metric logging
log_freq: 10
# Metrics to log (model / experiment dependent)
metrics_to_log:
  train:
    - "loss_objective"
  val:
    - "loss_objective"