checkpoints_dir: ${checkpoints_dir}
# How many epochs between checkpoint saving
save_freq: 1
# path to checkpoint
resume_checkpoint_path: null
# job id (useful for logging to same file or wandb run)
# default is null which means random id will be chosen
job_id: null