defaults:
  - default

model_id: backbone/dinov3
# alternatively, specify the Uniception preprocessor and set preprocess_image to false
data_norm_type: "identity"
model_config:
  backbone: "base"
  preprocess_images: true