defaults:
  - default

# String for model factory
model_str: "vggt"
# vggt normalizes internally
data_norm_type: "identity"
# Model config
model_config:
  # load specific patch embed
  pretrained_patch_embed_path: null
  # image size to train on
  # NOTE: can be overriden by training configs
  img_size: 518
  # patch size
  patch_size: 14
  # embed dim
  embed_dim: 1024
  # whether to train with a camera head
  enable_camera: true
  # whether to train with point head
  enable_point: true
  # whether to train with a depth head
  enable_depth: true
  # whether to train with a track head
  enable_track: true
  # aggregator config (e.g. change num_layers, patch embed type)
  # null => use vggt default
  aggregator_config: null
  # camera head config
  camera_head_config: null
  # depth head onfig
  depth_head_config: null
  # point head config
  point_head_config: null
  # track head config
  track_head_config: null