defaults:
  - default

num_views: 4

# Test Set
# Sample 20 multi-view sets from each scene
# ETH3D: 13 scenes
# ScanNet++V2: 30 scenes
# BlendedMVS: 43 scenes
# MVSSynth: 6 scenes
# Unrealstereo4k: 1 scene
test_dataset:
  "860 @ ${dataset.blendedmvs.val.dataset_str}
  + 120 @ ${dataset.mvs_synth.val.dataset_str}
  + 600 @ ${dataset.scannetppv2.val.dataset_str}
  + 260 @ ${dataset.eth3d.test.dataset_str}"