defaults:
  - default

num_views: 4

# Test Set
# Sample 20 multi-view sets from each scene
# ETH3D: 13 scenes
# ScanNet++V2: 30 scenes
# BlendedMVS: 43 scenes
# MVSSynth: 6 scenes
# Unrealstereo4k: 1 scene

# NOTE: only used blendedmvs and sppv2 because other datasets didn't have enough scenes
test_dataset:
  "860 @ ${dataset.blendedmvs.val.dataset_str}
  + 600 @ ${dataset.scannetppv2.val.dataset_str}"