defaults:
  - default

# Number of views parameter for the multi-view datasets
# default at 2 so one can run this config as-is for 2-view reconstructin
num_views: 2

# Test Resolution
resolution:
  val:
    eth3d: (518, 336)
    scannetppv2: (518, 336)

# Test Set
# Sample 10 multi-view sets from each scene
# ETH3D: 13 scenes
# ScanNet++V2: 30 scenes
test_dataset:
  "+ 130 @ ${dataset.eth3d.test.dataset_str}
  + 300 @ ${dataset.scannetppv2.test.dataset_str}"