defaults:
  - mvs_synth: mvs_synth
  - blendedmvs: blendedmvs
  - scannetppv2: scannetppv2
  - eth3d: eth3d

# Training Set, For example: BlendedMVS(split='train', resolution=(512, 384), transform=...)
train_dataset: ???
# Val and/or Test Set (assumes training and benchmarking scripts are separate)
test_dataset: "[null]"
# Number of workers for dataloader
num_workers: 8
# Default resolution for training
resolution_train: ???
# Default resolution for validation
resolution_val: ???
# Number of views parameter for multi-view datasets
num_views: 2
# Use a centered principal point for all images
principal_point_centered: false

train:
  variable_num_views: false
val:
  variable_num_views: false
test:
  variable_num_views: false