defaults:
  - default

# Maximum number of views parameter for the multi-view datasets
num_views: 4

train:
  # If True, the number of views can vary from batch to batch.
  # The maximum number of views is num_views and min is 2
  variable_num_views: true

# Training dataset
train_dataset:
  "+ 160_000 @ ${dataset.blendedmvs.train.dataset_str}
  + 80_000 @ ${dataset.mvs_synth.train.dataset_str}
  + 40_000 @ ${dataset.unrealstereo4k.train.dataset_str}"
# Validation dataset
test_dataset:
  "+ 4_000 @ ${dataset.blendedmvs.val.dataset_str}
  + 3_000 @ ${dataset.mvs_synth.val.dataset_str}
  + 1_00 @ ${dataset.unrealstereo4k.val.dataset_str}"