defaults:
  - resolution: resolution
  - logging: logging
  - checkpoint: checkpoint
  - distributed: distributed
  - optim: optim
  - loss: loss

#TODO distribute some into separtate files (e.g. losses, optimizer, distributed)
# Random Seed
seed: 42
# Maximum number of images per GPU (changes based on available GPU memory)
max_num_of_imgs_per_gpu: 48
# Use gradient accumulation if OOM issues
accum_steps: 1
# Maximum number of epochs
max_epochs: 20