# Single-view calibration is a special case of dense_n_view where 
# - we only eval ray_dirs_err_deg
# - we only do num_views: 1
# - we have multi-resolution sampling
defaults:
  - machine: default
  - model: vggt
  - dataset: benchmark_calibration
  - _self_

### Benchmarking args
seed: 0
# Disable CUDNN Benchmark (Disable for variable resolution & number of view training)
disable_cudnn_benchmark: true
# Batch size for inference (Metrics are computed per multi-view set and averaged, not per batch of multi-view sets)
batch_size: 24
# Use mixed precision for inference
amp:
  enabled: true
  amp_dtype: "bf16"

# Metrics
eval_metrics:
  - ray_dirs_err_deg

# Model
model:
  load_pretrained: true
checkpoint_path: null

output_dir: ${machine.results_dir}/single_view_calibration
root_data_dir: ${machine.root_data_dir}
mapanything_metadata_dir: ${machine.mapanything_metadata_dir}