defaults:
  - machine: default
  - model: vggt
  - dataset: benchmark_dense_n_view
  - _self_

### Benchmarking args
seed: 0
# Disable CUDNN Benchmark (Disable for variable resolution & number of view training)
disable_cudnn_benchmark: true
# Batch size for inference (Metrics are computed per multi-view set and averaged, not per batch of multi-view sets)
batch_size: 24
# Use mixed precision for inference
amp:
  enabled: true
  amp_dtype: bf16

# Metrics
eval_metrics:
  # points
  - pointmaps_abs_rel
  - pointmaps_inlier_thres_105
  # depth
  - z_depth_abs_rel
  - z_depth_inlier_thres_105
  # pose
  - pose_ate_rmse
  - pose_auc_30
  # calibration
  - ray_dirs_err_deg

# Num views
dataset:
  num_views: 4

# -- Model
model:
  load_pretrained: true
checkpoint_path: null

output_dir: ${machine.results_dir}/dense_n_view
root_data_dir: ${machine.root_data_dir}
mapanything_metadata_dir: ${machine.mapanything_metadata_dir}