defaults:
  - machine: clariden
  - model: vggtfeatureextractor
  - dataset: benchmark_multiview_correspondence
  - _self_

### Benchmarking args
seed: 0
# Disable CUDNN Benchmark (Disable for variable resolution & number of view training)
disable_cudnn_benchmark: true
# Batch size for inference (Metrics are computed per multi-view set and averaged, not per batch of multi-view sets)
batch_size: 20
# Use mixed precision for inference
amp:
  enabled: true
  amp_dtype: "bf16"

# Voxel size (creates dim / voxel_size spaced voxels in a given dimension)
voxel_sizes:
  - 0.7
  - 0.3

# Num views
dataset:
  num_views: 4

# Dirs
output_dir: ${machine.results_dir}/multiview_correspondence
root_data_dir: ${machine.root_data_dir}
mapanything_metadata_dir: ${machine.mapanything_metadata_dir}